# Generated by Django 4.1.3 on 2023-05-20 01:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0019_remove_clienteportelefono_descuento_mype_imagen'),
        ('gestionPedidos', '0002_pedido_pagorecibido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_texto', models.TextField(blank=True, default='', max_length=500)),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_cl', to='usuarios.cliente')),
                ('mype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.mype')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='gestionPedidos.pedido', unique=True)),
            ],
        ),
    ]
