# Generated by Django 4.1.3 on 2023-05-20 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_pedido_pagorecibido'),
        ('busquedaCotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.pedido'),
        ),
    ]
