# Generated by Django 4.1.3 on 2023-05-29 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busquedaCotizacion', '0004_solicitudcotizacion_mobiliarioporcotizar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoextracotizacion',
            name='pedido',
        ),
        migrations.AddField(
            model_name='cargoextracotizacion',
            name='solicitud',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='busquedaCotizacion.solicitudcotizacion'),
            preserve_default=False,
        ),
    ]
