# Generated by Django 4.1.3 on 2023-01-23 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=40)),
                ('apellido2', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='have_data',
            field=models.BooleanField(default=False),
        ),
    ]
