# Generated by Django 4.1.3 on 2023-01-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_usuario_have_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoPostal', models.CharField(max_length=5)),
                ('numInterior', models.CharField(max_length=15)),
                ('numExterior', models.CharField(max_length=15)),
                ('calle', models.CharField(max_length=40)),
                ('colonia', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('referencia', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='direcciones',
            field=models.ManyToManyField(to='usuarios.direccion'),
        ),
    ]
