# Generated by Django 4.1.3 on 2023-01-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_direccion_cliente_direcciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direcciones',
            field=models.ManyToManyField(blank=True, to='usuarios.direccion'),
        ),
    ]
