# Generated by Django 4.1.3 on 2023-02-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_cliente_direcciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
