# Generated by Django 4.1.3 on 2023-02-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_cliente_apellido2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='numInterior',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
