# Generated by Django 4.1.3 on 2023-02-10 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_direccion_numinterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mype',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombreEmpresa', models.CharField(max_length=50)),
                ('horaApertura', models.CharField(max_length=10)),
                ('horaCierre', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('direcciones', models.ManyToManyField(blank=True, to='usuarios.direccion')),
            ],
        ),
    ]
