# Generated by Django 4.1.3 on 2023-02-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_mype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mype',
            name='telefono',
            field=models.CharField(default='5555555555', max_length=10),
            preserve_default=False,
        ),
    ]
