# Generated by Django 4.1.3 on 2023-03-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_mype_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='mype',
            name='Instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mype',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mype',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
