# Generated by Django 4.1.3 on 2023-03-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_mype_instagram_mype_facebook_mype_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mype',
            old_name='Instagram',
            new_name='instagram',
        ),
    ]
