# Generated by Django 4.1.3 on 2023-03-27 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_rename_instagram_mype_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, null=True),
        ),
        migrations.CreateModel(
            name='ClienteWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePorTelefono',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.cliente')),
                ('descuento', models.FloatField()),
                ('mype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.mype')),
            ],
        ),
    ]
