# Generated by Django 4.1.3 on 2023-03-27 01:40

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Cliente = apps.get_model('usuarios', 'Cliente')
    for row in Cliente.objects.all():
        row.id = uuid.uuid4()
        row.save(update_fields=['id'])

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_cliente_usuario_cliente_id_clienteweb_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
