# Generated by Django 4.1.3 on 2023-03-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20230327_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_web',
            field=models.BooleanField(default=False),
        ),
    ]
