# Generated by Django 4.1.3 on 2023-03-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_cliente_is_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteportelefono',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='clienteportelefono',
            name='mype',
        ),
        migrations.RemoveField(
            model_name='clienteweb',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='clienteweb',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ClientePorTelefono',
        ),
        migrations.DeleteModel(
            name='ClienteWeb',
        ),
    ]
