# Generated by Django 4.1.3 on 2023-03-27 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_remove_clienteportelefono_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=40)),
                ('apellido2', models.CharField(blank=True, max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('is_web', models.BooleanField(default=False)),
                ('direcciones', models.ManyToManyField(blank=True, to='usuarios.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePorTelefono',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.cliente')),
                ('descuento', models.FloatField()),
                ('mype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.mype')),
            ],
        ),
    ]
