# Generated by Django 4.1.3 on 2023-03-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_cliente_clienteweb_clienteportelefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteportelefono',
            name='descuento',
            field=models.FloatField(default=0),
        ),
    ]
