# Generated by Django 4.1.3 on 2023-04-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_clienteportelefono_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(max_length=60),
        ),
    ]
