# Generated by Django 4.1.3 on 2023-05-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_direccion_calle_alter_direccion_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteportelefono',
            name='descuento',
        ),
        migrations.AddField(
            model_name='mype',
            name='imagen',
            field=models.ImageField(default='img/default.jpg', upload_to='img/'),
        ),
    ]
