# Generated by Django 4.1.3 on 2023-04-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0018_alter_direccion_calle_alter_direccion_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrega', models.DateTimeField()),
                ('fechaRecoleccion', models.DateTimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Por entregar', max_length=15)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('mype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.mype')),
            ],
        ),
        migrations.CreateModel(
            name='CargoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=60)),
                ('precio', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.pedido')),
            ],
        ),
    ]
