# Generated by Django 4.1.3 on 2023-04-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pagoRecibido',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
