# Generated by Django 4.1.3 on 2023-03-13 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0010_rename_instagram_mype_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('precioCompra', models.FloatField(blank=True)),
                ('precioRenta', models.FloatField(blank=True)),
                ('proveedor', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('mype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.mype')),
            ],
        ),
    ]
