# Generated by Django 4.1.3 on 2023-03-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiliario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='precioCompra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='precioRenta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='proveedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
