# Generated by Django 4.1.3 on 2023-03-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionInventario', '0002_alter_mobiliario_descripcion_alter_mobiliario_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiliario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
