# Generated by Django 4.1.3 on 2023-03-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionInventario', '0003_alter_mobiliario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobiliarioEnMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaFin', models.DateField(blank=True)),
                ('mobiliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionInventario.mobiliario')),
            ],
        ),
    ]
