# Generated by Django 4.1.3 on 2023-04-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionInventario', '0006_alter_mobiliarioenmantenimiento_fechafin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobiliarioRentado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
                ('mobiliario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionInventario.mobiliario')),
            ],
        ),
    ]
