# Generated by Django 4.1.3 on 2023-06-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionInventario', '0008_mobiliariorentado_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiliarioenmantenimiento',
            name='cobro',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='mobiliarioenmantenimiento',
            name='proveedor',
            field=models.CharField(blank=True, default='Varios proveedores', max_length=50),
        ),
    ]
