# Generated by Django 4.1.3 on 2023-06-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionInventario', '0009_mobiliarioenmantenimiento_cobro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiliario',
            name='proveedor',
            field=models.CharField(blank=True, default='Varios proveedores', max_length=50),
        ),
    ]
